version: '3.8'

services:
  web:
    container_name: dinesh-personal-website
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ../app/blog:/usr/share/nginx/html/blog:ro
      - ../app/images:/usr/share/nginx/html/images:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3 